name: CI
on: [push, pull_request]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install depdencies
        run: pip install setuptools pytest pytest-cov && python setup.py install
      - name: Run tests
        run: pytest
